### ISSUE TITLE
Drug/HOI selection confusion reported by some users - JS edit needed to guide them

### ISSUE THREAD

**Issue by rkboyce** [OHDSI/KnowledgeBaseWeb#4]
For the website, you may want to put in some simple JS to prevent throwing this type of error when the user tries to input a term manually instead of using the auto-completer.

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "diazepam"

I expect a bunch of people will be hitting the site after the presentation so this would be an easy fix with good benefit.

**Comment by blm14** [comment]
OK - added an is_numeric() check in IndexController to handle if the incoming search value is not a code and if so first pull the concept code for the relevant concept based on case-insensitive string matching in the relevant concept_class_id
